// Mock Knowledge Base for AI-Powered Diagnostic Chatbot
// This is the "brain" that the AI uses to diagnose and recommend services

export const servicesData = [
  {
    id: 1,
    name: "Deep Clean AC",
    category: "Air Conditioning",
    description: "Complete AC cleaning including filter, coils, and drain pipe. Removes dust, mold, and eliminates bad smells.",
    price: 599,
    duration: "1-2 hours",
    keywords: ["ac", "air conditioner", "cooling", "dust", "smell", "bad odor", "not cooling", "weak cooling", "split ac", "window ac"],
    symptoms: ["not cooling properly", "bad smell", "dust coming out", "weak airflow", "making noise", "water leaking"],
    providerId: 1,
    providerName: "CoolPro Services",
    rating: 4.8,
    image: "❄️"
  },
  {
    id: 2,
    name: "AC Gas Refill",
    category: "Air Conditioning",
    description: "Professional AC gas recharge and leak detection. Restores optimal cooling performance.",
    price: 1299,
    duration: "1 hour",
    keywords: ["ac", "gas", "refill", "freon", "leak", "not cooling", "warm air", "compressor"],
    symptoms: ["ac not cooling at all", "warm air coming", "ice formation", "gas leak", "low cooling"],
    providerId: 1,
    providerName: "CoolPro Services",
    rating: 4.9,
    image: "🌡️"
  },
  {
    id: 3,
    name: "Washing Machine Drum Checkup",
    category: "Appliances",
    description: "Diagnose and fix drum alignment issues, balance problems, and suspension repairs. Stops banging noises.",
    price: 499,
    duration: "45 mins",
    keywords: ["washing machine", "washer", "drum", "spinning", "noise", "banging", "shaking", "vibrating", "suspension"],
    symptoms: ["loud banging noise", "shaking violently", "drum not spinning", "uneven spinning", "door won't lock"],
    providerId: 2,
    providerName: "HomeFix Experts",
    rating: 4.7,
    image: "🧺"
  },
  {
    id: 4,
    name: "Washer Motor Repair",
    category: "Appliances",
    description: "Motor inspection, belt replacement, and repair. Fixes spin cycle issues and draining problems.",
    price: 899,
    duration: "2 hours",
    keywords: ["washing machine", "motor", "belt", "spin", "drain", "not draining", "not spinning", "washer"],
    symptoms: ["not spinning", "not draining", "motor burning smell", "loud grinding noise"],
    providerId: 2,
    providerName: "HomeFix Experts",
    rating: 4.6,
    image: "⚙️"
  },
  {
    id: 5,
    name: "5-Seater Sofa Shampoo Treatment",
    category: "Cleaning",
    description: "Deep cleaning for fabric sofas using shampoo extraction. Removes stains, odors, and allergens. Dries in 2 hours.",
    price: 899,
    duration: "2-3 hours",
    keywords: ["sofa", "couch", "furniture", "cleaning", "shampoo", "stain", "dirt", "fabric", "upholstery"],
    symptoms: ["dirty sofa", "stains on sofa", "bad smell", "spilled food", "pet hair", "dusty"],
    providerId: 3,
    providerName: "CleanMaster",
    rating: 4.9,
    image: "🛋️"
  },
  {
    id: 6,
    name: "Leather Sofa Cleaning & Conditioning",
    category: "Cleaning",
    description: "Specialized leather cleaning with conditioners to restore shine and prevent cracking.",
    price: 1499,
    duration: "2 hours",
    keywords: ["sofa", "leather", "couch", "conditioning", "polish", "cracking", "dull leather"],
    symptoms: ["dull leather", "cracks on leather", "stains on leather", "dry leather"],
    providerId: 3,
    providerName: "CleanMaster",
    rating: 4.8,
    image: "🛋️"
  },
  {
    id: 7,
    name: "Refrigerator Gas Refill",
    category: "Appliances",
    description: "Fridge gas recharge and cooling system check. Fixes cooling issues in both freezer and main compartment.",
    price: 999,
    duration: "1 hour",
    keywords: ["fridge", "refrigerator", "freezer", "gas", "cooling", "not cooling", "warm", "defrost"],
    symptoms: ["fridge not cooling", "freezer not freezing", "food spoiling", "ice melting", "compressor running continuously"],
    providerId: 4,
    providerName: "ApplianceCare",
    rating: 4.7,
    image: "🧊"
  },
  {
    id: 8,
    name: "Refrigerator Thermostat Repair",
    category: "Appliances",
    description: "Thermostat replacement and calibration. Fixes temperature control issues and erratic cooling.",
    price: 699,
    duration: "1 hour",
    keywords: ["fridge", "refrigerator", "thermostat", "temperature", "control", "too cold", "too warm", "freezing food"],
    symptoms: ["temperature fluctuating", "food freezing in fridge", "fridge too warm", "not maintaining temperature"],
    providerId: 4,
    providerName: "ApplianceCare",
    rating: 4.5,
    image: "🌡️"
  },
  {
    id: 9,
    name: "Kitchen Sink Drain Unblock",
    category: "Plumbing",
    description: "Professional drain cleaning using snaking and techniques. Clears stubborn clogs and prevents backups.",
    price: 399,
    duration: "30 mins",
    keywords: ["sink", "drain", "clog", "block", "plumbing", "water not draining", "standing water", "kitchen"],
    symptoms: ["sink not draining", "water backing up", "bad smell from drain", "gurgling sound", "slow drainage"],
    providerId: 5,
    providerName: "PlumFast",
    rating: 4.6,
    image: "🚿"
  },
  {
    id: 10,
    name: "Bathroom Drain Cleaning",
    category: "Plumbing",
    description: "Clears hair, soap scum, and debris from bathroom drains. Includes preventive treatment.",
    price: 449,
    duration: "30-45 mins",
    keywords: ["drain", "bathroom", "shower", "tub", "clog", "hair", "slow draining", "plumbing"],
    symptoms: ["shower draining slowly", "water pooling", "hair clog", "bad drain odor"],
    providerId: 5,
    providerName: "PlumFast",
    rating: 4.7,
    image: "🚿"
  },
  {
    id: 11,
    name: "Ceiling Fan Installation",
    category: "Electrical",
    description: "Professional ceiling fan mounting with wiring and balance check. Includes all mounting hardware.",
    price: 549,
    duration: "1-2 hours",
    keywords: ["fan", "ceiling fan", "installation", "electrical", "wiring", "mounting", "hanging"],
    symptoms: ["need new fan", "fan not working", "wobbly fan", "replacing old fan"],
    providerId: 6,
    providerName: "ElectroSafe",
    rating: 4.8,
    image: "🌀"
  },
  {
    id: 12,
    name: "Switch & Socket Repair",
    category: "Electrical",
    description: "Repair or replace damaged switches and sockets. Fixes loose connections, sparks, and non-working points.",
    price: 199,
    duration: "30 mins",
    keywords: ["switch", "socket", "electrical", "outlet", "spark", "loose", "not working", "power"],
    symptoms: ["switch not working", "sparking switch", "loose socket", "socket overheating", "no power"],
    providerId: 6,
    providerName: "ElectroSafe",
    rating: 4.5,
    image: "🔌"
  },
  {
    id: 13,
    name: "Microwave Magnetron Replacement",
    category: "Appliances",
    description: "Replace magnetron to restore heating capability. Complete diagnosis and testing included.",
    price: 1599,
    duration: "1 hour",
    keywords: ["microwave", "not heating", "magnetron", "no heat", "running but not heating"],
    symptoms: ["microwave not heating", "sparks inside", "loud buzzing", "plate not turning"],
    providerId: 4,
    providerName: "ApplianceCare",
    rating: 4.4,
    image: "📦"
  },
  {
    id: 14,
    name: "Geyser Heating Element Replacement",
    category: "Electrical",
    description: "Replace faulty heating element in water heater/geyser. Restores hot water supply.",
    price: 899,
    duration: "1 hour",
    keywords: ["geyser", "water heater", "heating element", "hot water", "no hot water", "cold water"],
    symptoms: ["no hot water", "water not heating", "geyser not working", "taking too long to heat"],
    providerId: 6,
    providerName: "ElectroSafe",
    rating: 4.7,
    image: "♨️"
  },
  {
    id: 15,
    name: "Carpet Deep Cleaning",
    category: "Cleaning",
    description: "Deep steam cleaning for carpets. Removes embedded dirt, stains, and allergens. Quick drying.",
    price: 599,
    duration: "1-2 hours",
    keywords: ["carpet", "rug", "cleaning", "steam", "stains", "dirt", "deep clean"],
    symptoms: ["dirty carpet", "stains on carpet", "bad carpet smell", "spilled liquid", "pet stains"],
    providerId: 3,
    providerName: "CleanMaster",
    rating: 4.8,
    image: "🟫"
  },
  {
    id: 16,
    name: "Pipe Leak Repair",
    category: "Plumbing",
    description: "Fix leaking pipes including water lines, drain pipes, and fittings. Leak detection and repair.",
    price: 699,
    duration: "1-2 hours",
    keywords: ["pipe", "leak", "plumbing", "dripping", "water leak", "burst pipe", "fitting"],
    symptoms: ["water leaking", "dripping pipe", "wet wall", "low water pressure", "water damage"],
    providerId: 5,
    providerName: "PlumFast",
    rating: 4.6,
    image: "🔧"
  }
]

export const providersData = [
  {
    id: 1,
    name: "CoolPro Services",
    specialty: "Air Conditioning",
    rating: 4.8,
    reviews: 234,
    services: 2,
    verified: true
  },
  {
    id: 2,
    name: "HomeFix Experts",
    specialty: "Home Appliances",
    rating: 4.7,
    reviews: 189,
    services: 2,
    verified: true
  },
  {
    id: 3,
    name: "CleanMaster",
    specialty: "Professional Cleaning",
    rating: 4.9,
    reviews: 312,
    services: 3,
    verified: true
  },
  {
    id: 4,
    name: "ApplianceCare",
    specialty: "Appliance Repair",
    rating: 4.6,
    reviews: 156,
    services: 3,
    verified: true
  },
  {
    id: 5,
    name: "PlumFast",
    specialty: "Plumbing Services",
    rating: 4.7,
    reviews: 198,
    services: 3,
    verified: true
  },
  {
    id: 6,
    name: "ElectroSafe",
    specialty: "Electrical Work",
    rating: 4.6,
    reviews: 145,
    services: 3,
    verified: true
  }
]